package com.example.flight.v1.configure;                                                                                                                                                                  
                                                                                                                                                                                                            
  import org.springframework.context.annotation.Bean;                                                                                                                                                       
  import org.springframework.context.annotation.Configuration;                                                                                                                                              
  import org.springframework.web.cors.CorsConfiguration;                                                                                                                                                    
  import org.springframework.web.cors.UrlBasedCorsConfigurationSource;                                                                                                                                      
  import org.springframework.web.filter.CorsFilter;                                                                                                                                                         
                                                                                                                                                                                                            
  import java.util.Arrays;                                                                                                                                                                                  
                                                                                                                                                                                                            
  @Configuration                                                                                                                                                                                            
  public class CorsConfig {                                                                                                                                                                                 
                                                                                                                                                                                                            
      @Bean                                                                                                                                                                                                 
      public CorsFilter corsFilter() {                                                                                                                                                                      
          CorsConfiguration config = new CorsConfiguration();                                                                                                                                               
                                                                                                                                                                                                            
          // Allow these origins                                                                                                                                                                            
          config.setAllowedOrigins(Arrays.asList(                                                                                                                                                           
              "http://localhost:4200",                                                                                                                                                                      
              "http://localhost:3000",                                                                                                                                                                      
              "https://flightbookingui.onrender.com",                                                                                                                                                       
              "https://flightbooking-1b9k.onrender.com"                                                                                                                                                     
          ));                                                                                                                                                                                               
                                                                                                                                                                                                            
          // Allow all HTTP methods                                                                                                                                                                         
          config.setAllowedMethods(Arrays.asList("GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"));                                                                                                      
                                                                                                                                                                                                            
          // Allow all headers                                                                                                                                                                              
          config.setAllowedHeaders(Arrays.asList("*"));                                                                                                                                                     
                                                                                                                                                                                                            
          // Allow credentials (cookies, auth headers)                                                                                                                                                      
          config.setAllowCredentials(true);                                                                                                                                                                 
                                                                                                                                                                                                            
          // How long the browser should cache CORS response                                                                                                                                                
          config.setMaxAge(3600L);                                                                                                                                                                          
                                                                                                                                                                                                            
          UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();                                                                                                                   
          source.registerCorsConfiguration("/**", config);                                                                                                                                                  
                                                                                                                                                                                                            
          return new CorsFilter(source);                                                                                                                                                                    
      }                                                                                                                                                                                                     
  }
